name: CreateRelease

# Create a release with the version number being one greater than the last findable version
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create_release"
  create_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        run: echo "Hello, world!"

